# Generated by Django 5.0.6 on 2025-03-07 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GlobalSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_provider_number', models.BigIntegerField(default=100000000000)),
            ],
        ),
        migrations.AlterField(
            model_name='service',
            name='icon_link',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='service',
            name='name',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='serviceprovider',
            name='name',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='serviceprovider',
            name='profile_pic',
            field=models.TextField(),
        ),
    ]
