# Generated by Django 5.0.6 on 2025-03-08 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_globalsettings_alter_service_icon_link_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='icon_link',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='serviceprovider',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='serviceprovider',
            name='profile_pic',
            field=models.TextField(blank=True, null=True),
        ),
    ]
