# Generated by Django 5.0.6 on 2025-03-16 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0003_alter_service_icon_link_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='serviceprovider',
            name='availability',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='serviceprovider',
            name='rating',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
    ]
