# Generated by Django 5.0.6 on 2025-04-25 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0005_serviceprovider_experience'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='order',
            field=models.IntegerField(default=0),
        ),
    ]
