# Generated by Django 5.0.6 on 2025-04-25 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0006_service_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='serviceprovider',
            name='service',
        ),
        migrations.AddField(
            model_name='serviceprovider',
            name='services',
            field=models.ManyToManyField(related_name='providers', to='services.service'),
        ),
    ]
