# Generated by Django 5.0.6 on 2025-04-27 09:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0009_comments'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comments',
            name='service_receiver_name',
        ),
    ]
