# Generated by Django 5.0.6 on 2025-04-27 09:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0010_remove_comments_service_receiver_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerrequest',
            name='service_provider',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='customer_requests', to='services.serviceprovider'),
        ),
    ]
